### ISSUE TITLE
在文档中心首页，能否加个目录，个人进入这个文档中心的时候感觉好像只有一个MASA Stack的文档

### ISSUE THREAD

**Issue by MapleWithoutWords** [masastack/MASA.Docs#118]
![image](https://user-images.githubusercontent.com/38368335/215972344-1336db4a-a589-4589-8423-9d024a8d3106.png)

**Comment by doddgu** [comment]
Yes, we designed it. But it will take a little more time.

**Comment by doddgu** [comment]
If you are interested, you can also pr and we can send you the design draft.

**Comment by MapleWithoutWords** [comment]
Ok, Ok, I have a try.

> If you are interested, you can also pr and we can send you the design draft.

**Comment by doddgu** [comment]
![image](https://user-images.githubusercontent.com/7299249/216524012-8c117e46-c4f3-498c-938a-18ea851fb451.png)

@MapleWithoutWords this is the design draft.

**Comment by MapleWithoutWords** [comment]
> ![image](https://user-images.githubusercontent.com/7299249/216524012-8c117e46-c4f3-498c-938a-18ea851fb451.png)
> 
> @MapleWithoutWords this is the design draft.

@doddgu  ok，if many version,so the need separate each version document
![image](https://user-images.githubusercontent.com/38368335/220253732-1d4b456d-312f-4601-be31-da2bc0c6d597.png)

**Comment by doddgu** [comment]
We just need publish the version, and jumt to the site. Keep the documnet newest.

**Comment by MapleWithoutWords** [comment]
already push request:https://github.com/BlazorComponent/MASA.Blazor/pull/1027
