### ISSUE TITLE
文档模板，右边组件库菜单显示不全

### ISSUE THREAD

**Issue by kesshei** [masastack/MASA.Docs#13]
![a6c1a570e72419cec8be108f1945c74](https://user-images.githubusercontent.com/6630768/193274251-cec6cb47-bd61-46b8-95aa-c13236554421.jpg)

短期的方式的话，可以往前调整一下。

**Comment by zhenlei520** [comment]
十分感谢你的建议，这块我们后面尝试调整一下，我们已经在开始准备新的文档站点的开发工作，目前文档站点暂时使用的开源的模板，其中小问题挺多的，等后期文档站点开发完成后会逐渐迁移到新的站点，会有全新的文档体验

**Comment by doddgu** [comment]
临时的文档站点只需要关注文档内容即可，谢谢反馈。
