### ISSUE TITLE
多级缓存描述不正确

### ISSUE THREAD

**Issue by kesshei** [masastack/MASA.Docs#14]
![21a2cb7659d729c9dbfb61c35f82c63](https://user-images.githubusercontent.com/6630768/193275664-ac92ed1e-86ca-4622-bd31-d9aa63343434.jpg)
用分布式缓存更为明确。

**Comment by zhenlei520** [comment]
目前这里的功能多数人喜欢称为二级缓存，或分布式内存缓存，但分布式内存缓存与微软定义的分布式内存缓存存在二意性，为了方便理解，不增加学习成本，考虑到后期会增加其它支持，暂定为多级缓存

**Comment by zhenlei520** [comment]
目前这里的功能多数人喜欢称为二级缓存，或分布式内存缓存，但分布式内存缓存与微软定义的分布式内存缓存存在二意性，为了方便理解，不增加学习成本，考虑到后期会增加其它支持，暂定为多级缓存

原本包有歧义，会被误以为是内存缓存，目前0.6.0中包已重新更名，调整为'Masa.Contrib.Caching.MultilevelCache'

**Comment by doddgu** [comment]
已修复 #15
