### ISSUE TITLE
文档代码块支持背景高亮

### ISSUE THREAD

**Issue by MapleWithoutWords** [masastack/MASA.Docs#161]
能否给代码块某行增加透明背景，用于说明我这行是新增的
![企业微信截图_16818912406656](https://user-images.githubusercontent.com/38368335/233010365-146d53e8-b89f-45b8-92f0-69a75bb86642.png)

**Comment by doddgu** [comment]
先让ux出效果图，这个 @zhenlei520 也需要的功能吧
@capdiem  PTAL

**Comment by zhenlei520** [comment]
> 先让ux出效果图，这个 @zhenlei520 也需要的功能吧 @capdiem PTAL

是的  除此之外，增加内容、删除内容如果可以区分出来会更好，那样就不需要用code-group来处理这类问题了

**Comment by capdiem** [comment]
增加删除用diff。

```
```diff
- PopupService.AlertAsync()
- PopupService.ToastAsync()
+ PopupService.EnqueueSnackbarAsync()
```

**Comment by doddgu** [comment]
贴一个渲染过的完整的例子看下吧

**Comment by capdiem** [comment]
diff: https://docs.masastack.com/blazor/getting-started/upgrade-guide

**Comment by doddgu** [comment]
我的意思是类似于
```
```csharp
int a = 0;
+ int a = 1;
int b = 1;
- b++;
int c = a + b; //怎么加背景色
```

**Comment by MapleWithoutWords** [comment]
我没法接受这种用法，跟ux的图也不太像，有点淘宝买家秀跟卖家秀 @capdiem @doddgu ：
·1. 我的代码块是csharp，还必须我用diff
 2. 新增行没有背景高亮
 3. 复制代码的时候，会把+，-号复制出来
![image](https://user-images.githubusercontent.com/38368335/233844015-da3ccda7-51e7-417d-8c1c-ecedbb654258.png)

**Comment by capdiem** [comment]
@MapleWithoutWords 你看关闭此 issue的 PR。

**Comment by doddgu** [comment]
![image](https://user-images.githubusercontent.com/7299249/233906392-ceb3c9ee-c74b-483b-ba64-e038d7fe6a2e.png)
