### ISSUE TITLE
code-group不支持代码高亮

### ISSUE THREAD

**Issue by zhenlei520** [masastack/MASA.Docs#184]
## Description

   :::: code-group
   ::: code-group-item 安装Swagger包

   ```shell 终端
   dotnet add package Swashbuckle.AspNetCore
   ```

   :::
   ::: code-group-item 修改 Program.cs，注册并使用Swagger

   ```csharp Program.cs l:5-6,16-17
   var builder = WebApplication.CreateBuilder(args);
   
   #region Register Swagger
   
   builder.Services.AddEndpointsApiExplorer();
   builder.Services.AddSwaggerGen();
   
   #endregion
   
   var app = builder.AddServices();
   
   #region Use Swagger
   
   if (app.Environment.IsDevelopment())
   {
       app.UseSwagger();
       app.UseSwaggerUI();
   }
   
   #endregion
   
   app.MapGet("/", () => "Hello World!");
   
   app.Run();
   ```
   :::
   ::::

![image](https://user-images.githubusercontent.com/9740886/234033394-68c51755-0018-4746-99b0-ba8a0ebd30b4.png)

![image](https://user-images.githubusercontent.com/9740886/234032883-689ec579-7c91-4319-8934-a49fb659564e.png)

Related Issues：[issues-161](https://github.com/masastack/MASA.Docs/issues/161)

## Expect

![image](https://user-images.githubusercontent.com/9740886/234033572-e4010064-0229-4ced-a90e-d7fd7766c526.png)

**Comment by capdiem** [comment]
@zhenlei520 我这里是可以的，你再试试？

**Comment by capdiem** [comment]
@zhenlei520 我知道了，第一个tab是能显示的，其他的不能。
