### ISSUE TITLE
1.0.0-rc Web应用程序文档问题反馈

### ISSUE THREAD

**Issue by jojinshallar** [masastack/MASA.Docs#213]
发现1.0的文档有些瑕疵，详细请见下面链接：
https://note.youdao.com/s/4tIipABB

**Comment by doddgu** [comment]
@zhenlei520 @MapleWithoutWords PTAL

**Comment by MapleWithoutWords** [comment]
1. 第一个问题是没有发布
2. 第二个已修改
3. 模板也需要重新发布下
4.
