### ISSUE TITLE
_userCaller是哪来的

### ISSUE THREAD

**Issue by sunday866** [masastack/MASA.Docs#217]
[ApiController]
[Route("api/[controller]/[action]")]
public class UserController : ControllerBase
{
    private readonly ICaller _caller;

    public UserController(ICaller caller) => _caller = caller;

    public async Task<IActionResult> HelloAsync(int userId)
    {
        var userObj = await _userCaller.HelloAsync("word");
        return Ok(userObj);
    }
}

**Comment by zhenlei520** [comment]
没有`_userCaller`，它应该是`_caller`，方便的话提个`pr`
