### ISSUE TITLE
文档中快速入门-web应用程序的建议

### ISSUE THREAD

**Issue by trustme2016** [masastack/MASA.Docs#227]
## Description

1、创建项目时“dotnet add ./TodoApp.Web/TodoApp.Web.csproj package Masa.Contrib.Service.Caller.HttpClient -v 1.0.0-rc.1" 因为用了rc版的包，所以需要在NuGet包管理器中要勾选包括预发行版。不然提示无法找到“Masa.Contrib.Service.Caller.HttpClient -v 1.0.0-rc.1” 建议此处可以提示“需要在NuGet包管理器中要勾选包括预发行版”

2、文档中缺少生成数据库那一步，对新手来说不太友好

**Comment by MayueCif** [comment]
已经统一升级1.0.0版本
