### ISSUE TITLE
读写分离章节文档问题

### ISSUE THREAD

**Issue by jojinshallar** [masastack/MASA.Docs#238]
## Description
![image](https://github.com/masastack/MASA.Docs/assets/9363582/cd784b1f-e5dd-427d-a043-5877be9ba70c)
![image](https://github.com/masastack/MASA.Docs/assets/9363582/121c0147-87c7-439b-a12f-23e31c14eb41)

（1）因为AddEventBus()扩展方法是在Masa.Contrib.Dispatcher.Events/Extensions/ServiceCollectionExtensions.cs中定义的，所以应该引用【Masa.Contrib.Dispatcher.Events】。
（2）下文使用了MinimalApi中的ServiceBase，应该添加引用【Masa.Contrib.Service.MinimalAPIs】。

**Comment by MayueCif** [comment]
已修复
