### ISSUE TITLE
组件的按钮内容和给出的代码大小写不匹配

### ISSUE THREAD

**Issue by 1059444616** [masastack/MASA.Docs#68]
![image](https://user-images.githubusercontent.com/108256393/210748472-a939ba41-5567-47fb-ad39-6ac8a7a5ec00.png)
异常处理-是否展示异常
其他按钮也有这个问题

**Comment by codding-y** [comment]
默认行为

**Comment by doddgu** [comment]
这个是按钮的默认行为，如果要区分大小写可以增加class `text-capitalize`
